Build the patch using Drupal distribution files
Otherwise, the modules' .info files do not get
the right version info included in them.

diff --git a/make_drupal_upgrade_patch b/make_drupal_upgrade_patch
--- a/make_drupal_upgrade_patch
+++ b/make_drupal_upgrade_patch
@@ -2,15 +2,16 @@
 
 
 Usage () { cat >&2 <<EOF
-Usage: $0 <version>
-Make a patch to upgrade from current Drupal version
+Usage: $0 <from_version> <to_version>
+Make a patch from one version of Drupal to another
 EOF
 }
 
 
-# Drupal repository
-DRUPAL_REMOTE_URL='https://git.drupal.org/project/drupal.git'
-
+# URL for Drupal distributions
+DRUPAL_DIST_URL_PREFIX='https://ftp.drupal.org/files/projects/'
+# Extension for Drupal distribution files
+DRUPAL_DIST_FILE_EXT=.tar.gz
 # Drupal files that should be excluded
 DISPOSABLES=(
   [6]='CHANGELOG.txt COPYRIGHT.txt INSTALL.mysql.txt INSTALL.pgsql.txt install.php INSTALL.txt LICENSE.txt MAINTAINERS.txt UPGRADE.txt'
@@ -20,15 +21,17 @@ DISPOSABLES=(
 
 set -e
 
-if [ $# -ne 1 ] ; then
+if [ $# -ne 2 ] ; then
   Usage
   exit 1
 fi
 
-if ! [[ "$1" =~ ^[0-9]+\.[0-9]+$ ]] ; then
-  Usage
-  exit 1
-fi
+for version ; do
+  if ! [[ "$version" =~ ^[0-9]+\.[0-9]+$ ]] ; then
+    Usage
+    exit 1
+  fi
+done
 
 
 Error () {
@@ -36,64 +39,58 @@ Error () {
 }
 
 
-guess_drupal_core_version () {
-  #drupal-6.30/modules/system/system.module:define('VERSION', '6.30');
-  #drupal-7.26/includes/bootstrap.inc:define('VERSION', '7.26');
-  local guess_files=( modules/system/system.module includes/bootstrap.inc )
-  local guess_file
-  for guess_file in "${guess_files[@]}" ; do
-    if ! [[ -r "${guess_file}" ]] ; then
-      Error "Expected to find file '${guess_file}'."
-      Error 'Is the current directory a Drupal root?'
-      Usage
-      exit 1
-    fi
-  done
-  local guess=$(
-      cat "${guess_files[@]}" \
-      | grep '\<define\>.*\<VERSION\>' \
-      | tr -dc 0-9.
-    )
-  if [[ -z "${guess}" ]] ; then
-    Error 'Unable to guess Drupal core version.'
-    exit 1
+download_drupal_dist () {
+  local version=$1
+  local dist_file_name=drupal-${version}${DRUPAL_DIST_FILE_EXT}
+  local dist_url=${DRUPAL_DIST_URL_PREFIX}${dist_file_name}
+
+  if ! [ -f "$dist_file_name" ] ; then
+    wget \
+      --verbose \
+      --timestamping \
+      --timeout=300 \
+      "$dist_url"
   fi
-  printf '%s\n' "${guess}"
+
+  printf '%s\n' "$dist_file_name"
 }
 
 
-target_version=$1
-current_version=$( guess_drupal_core_version )
+extract_drupal_dist () {
+  local dist_file_name=$1
+  local extracted_path=$( basename "$dist_file_name" ${DRUPAL_DIST_FILE_EXT} )
 
-major_version=${current_version%%.*}
-if ! [ "$major_version" = "${target_version%%.*}" ] ; then
-  Error "Mismatched versions: $current_version -> $target_version"
+  if [ -d "$extracted_path" ] ; then
+    echo >&2 "Error: Extracted copy already exists? '$extracted_path'"
+    exit 2
+  fi
+
+  tar xf "$dist_file_name"
+
+  printf '%s\n' "$extracted_path"
+}
+
+
+from_version=$1
+to_version=$2
+
+major_version=${from_version%%.*}
+if ! [ "$major_version" = "${to_version%%.*}" ] ; then
+  Error "Mismatched major versions: $from_version -> $to_version"
   exit 2
 fi
 
-patch_file_name=upgrade_drupal-${current_version}-${target_version}.patch
-cleanup_current=cleanup_${current_version}
-cleanup_target=cleanup_${target_version}
+patch_file_name=upgrade_drupal-${from_version}-${to_version}.patch
 
+from_dist=$( download_drupal_dist "$from_version" )
+to_dist=$( download_drupal_dist "$to_version" )
 
-# Is the current directory a git working tree?
-git status > /dev/null || exit $?
+from_extracted=$( extract_drupal_dist "$from_dist" )
+to_extracted=$( extract_drupal_dist "$to_dist" )
 
-# Add git remote for Drupal repository
-git remote get-url drupal 2>/dev/null >/dev/null \
-  || git remote add drupal "$DRUPAL_REMOTE_URL"
-git fetch drupal
+for extracted in "$from_extracted" "$to_extracted" ; do
+  ( cd "$extracted" && rm ${DISPOSABLES[$major_version]} )
+done
 
-# Create cleaned up version of current tag
-git checkout -b "$cleanup_current" "$current_version" >/dev/null
-git rm ${DISPOSABLES[$major_version]} >/dev/null
-git commit -m "Clean up $current_version" >/dev/null
-
-# Create cleaned up version of upgrade tag
-git checkout -b "$cleanup_target" "$target_version" >/dev/null
-git rm ${DISPOSABLES[$major_version]} >/dev/null
-git commit -m "Clean up $target_version" >/dev/null
-
-# Create patch
-git diff -u "$cleanup_current" "$cleanup_target" > "$patch_file_name"
+diff -ru "$from_extracted" "$to_extracted" > "$patch_file_name"
 printf '%s\n' "$patch_file_name"
